### ISSUE TITLE
Place this code in V Ex Electronics Website.

### ISSUE THREAD

**Issue by dkkaran1996** [vac-soft/vexelectronics#40]
### Kindly place the below code in Website after head section of each page this is for V Ex Site
`<!-- Google tag (gtag.js) --> <script async src="https://www.googletagmanager.com/gtag/js?id=G-TZFEPT095C&quot;></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-TZFEPT095C'); </script>`

**Comment by Srinivasan260** [comment]
#41 done (updated google analysis)

**Comment by Srinivasan260** [comment]
#41 updated with google analysis
